<a href="https://colab.research.google.com/github/Shreshth-112/100_Days_of_Machine_Learning/blob/main/DAY_27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ONE HOT ENCODING
---

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.sample(5)

        brand  km_driven    fuel                 owner  selling_price
5205  Hyundai     120000  Diesel          Second Owner         880000
4759    Honda      39000  Diesel           First Owner         885000
2113  Hyundai     120000  Petrol  Fourth & Above Owner         100000
5320   Maruti      50000  Petrol          Second Owner         210000
2107   Maruti     110000  Diesel           First Owner         590000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [10]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [11]:
df['brand'].nunique()

32

In [12]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [13]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# 1. One Hot Encoding Using Pandas

In [16]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int,drop_first=True)
# Implemented OneHot Encoding and dropped the first column.

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

# 2. ONE HOT ENCODING USING **SKLEARN**
---

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2, random_state=2)

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
ohe = OneHotEncoder(drop = 'first', sparse_output = False, dtype=np.int32)

In [35]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])
X_test_new = ohe.fit_transform(X_train[['fuel','owner']])

In [36]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

# 4. OneHotEncoding with Top Categories
---

In [37]:
counts = df['brand'].value_counts()

In [38]:
df['brand'].nunique()
threshold = 100

In [39]:
repl = counts[counts <= threshold].index

In [41]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype=np.int32).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
7096,0,0,1,0,0,0,0,0,0,0,0,0,0
6687,0,0,0,0,0,0,1,0,0,0,0,0,0
5752,0,0,0,0,0,1,0,0,0,0,0,0,0
208,0,0,0,0,0,0,1,0,0,0,0,0,0
2782,0,0,0,0,0,1,0,0,0,0,0,0,0